-
  name: install rabbitmq on ubuntu 
  hosts: localhost
  become: yes
  task:
    - name: Import PackageCloud signing key
      command: wget -O - "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey" | sudo apt-key add -

    - name: Apt update
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name: curl, gnupg

    - name: Add RabbitMQ signing key
      command: curl -fsSL https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc | sudo apt-key add -

    - name: Install apt HTTPS transport
      apt:
        name: apt-transport-https
    
    - name: Add Bintray repositories 
      command: sudo tee /etc/apt/sources.list.d/bintray.rabbitmq.list <<EOF
              deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang-22.x
              deb https://dl.bintray.com/rabbitmq/debian bionic main
              EOF

    - name: Update package
      apt:
        update_cache: yes

    - name: Install rabbitmq-server and its dependencies
      apt:
        name: rabbitmq-server
