- 
  name: Install rabbitmq
  hosts: localhost

  tasks:
    - name: Import PackageCloud signing key
      apt_key:
        url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
        state: present

    - name: Apt update
      apt:
        update_cache: yes
      become: yes

    - name: Install prerequisites
      apt:
        name: curl, gnupg
      become: yes

    - name: Add RabbitMQ signing key
      apt_key:
        url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
        state: present

    - name: Install apt HTTPS transport
      apt:
        name: apt-transport-https
      become: yes
    
    - name: Add Bintray repositories 1
      file:
        path: /etc/apt/sources.list.d/bintray.rabbitmq.list
        state: touch
      become: yes
      
    - name: Add Bintray repositories 2
      apt_repository:
        repo: deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang-22.x
        state: present
        filename: bintray.rabbitmq.list

    - name: Add Bintray repositories 3
      apt_repository:
        repo: deb https://dl.bintray.com/rabbitmq/debian bionic main
        state: present
        filename: bintray.rabbitmq.list

    - name: Update package
      apt:
        update_cache: yes
      become: yes

    - name: Install rabbitmq-server and its dependencies
      apt:
        name: rabbitmq-server
      become: yes
