-
  name: config rabbitmq
  host: localhost

  task:
    - name: Start the rabbitmq server
      systemd:
        name: rabbitmq-server
        state: started
        enabled: yes
    
    - name: Create rabbitmq admin account
      command: sudo rabbitmqctl add_user admin admin

    - name: Set user tag
      command: sudo rabbitmqctl set_user_tags admin administrator

    - name: Set permissions
      command: sudo rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"

    - name: Enable RabbitMQ management console
      command: sudo rabbitmq-plugins enable rabbitmq_management

    - name: Enable RabbitMQ management console 2
      command: sudo chown -R rabbitmq:rabbitmq /var/lib/rabbitmq/

    - name: Create an administrator user account for accessing RBMQ management console
      command: sudo rabbitmqctl add_user mqadmin mqadmin

    - name: Set user tag
      command: sudo rabbitmqctl set_user_tags mqadmin administrator

    - name: Set permissions
      command: sudo rabbitmqctl set_permissions -p / mqadmin “.*” “.*” “.*”